# Generated by Django 6.0.7 on 2026-07-23 20:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_number', models.CharField(db_index=True, max_length=30, unique=True)),
                ('status', models.CharField(choices=[('assigned', 'Assigned'), ('picked_up', 'Picked Up'), ('in_transit', 'In Transit'), ('delivered', 'Delivered'), ('failed', 'Failed')], default='assigned', max_length=20)),
                ('proof_image', models.ImageField(blank=True, null=True, upload_to='delivery_proofs/')),
                ('notes', models.TextField(blank=True)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('picked_up_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('agent', models.ForeignKey(limit_choices_to={'role': 'DELIVERY_AGENT'}, on_delete=django.db.models.deletion.PROTECT, related_name='delivery_assignments', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(blank=True, help_text='Set for multi-stop pickup (one agent, whole order)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='delivery_assignments', to='orders.order')),
                ('suborder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='delivery_assignments', to='orders.suborder')),
            ],
            options={
                'db_table': 'delivery_assignments',
            },
        ),
        migrations.CreateModel(
            name='DeliveryLocationPing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('lng', models.DecimalField(decimal_places=6, max_digits=9)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_pings', to='shipping.deliveryassignment')),
            ],
            options={
                'db_table': 'delivery_location_pings',
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='deliveryassignment',
            index=models.Index(fields=['agent', 'status'], name='delivery_as_agent_i_abeb42_idx'),
        ),
    ]
